[theme]
base = "dark"
primaryColor = "#FF9900"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#FFB000"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[browser]
gatherUsageStats = false

[server]
headless = true
